create TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

create TABLE IF NOT EXISTS requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  description VARCHAR(255) NOT NULL,
  requestor_id VARCHAR(512) NOT NULL,
  CONSTRAINT pk_request PRIMARY KEY (id),
  CONSTRAINT request_requestor_id_fk FOREIGN KEY (requestor_id) REFERENCES users(id) ON delete CASCADE
);

create TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(512) NOT NULL,
  is_available boolean NOT NULL,
  owner_id  BIGINT NOT NULL REFERENCES users(id) ON delete CASCADE,
  request_id BIGINT NOT NULL REFERENCES requests(id) ON delete CASCADE,
  CONSTRAINT pk_item PRIMARY KEY (id)
--  CONSTRAINT item_id_user_fk FOREIGN KEY (id_user) REFERENCES users(user_id) ON delete CASCADE
);